### ISSUE TITLE
[重要] 與自動建置相關

### ISSUE THREAD

**Issue by Incheat** [torpedo228/yola#1]
到Settings修改Github Pages的設定喔

Build and deployment - Source
Deploy from branch -> GitHub Actions

設定GitHub Actions完後以後local端就不用build上傳docs了，直接更新source code就會在Github伺服器自動CI/CD

**Comment by Incheat** [comment]
設定完後以後local端就不用build上傳docs了，直接更新source code會自動CI/CD

**Comment by torpedo228** [comment]
回報禿頭教官!任務已完成!馬上來試試!
![狸貓兔子](https://github.com/torpedo228/yola/assets/114288108/2a61841f-f871-46c7-990d-922edd4b23aa)

**Comment by torpedo228** [comment]
報告禿頭教官!
實作成功!
![狸貓超目中無人](https://github.com/torpedo228/yola/assets/114288108/e7b4d4f2-8f47-43f5-b471-c40f8fac1dd9)

**Comment by Incheat** [comment]
LGTM
